### ISSUE TITLE
add !w.tickle

### ISSUE THREAD

**Issue by DasWolke** [DasWolke/rem-v2#81]

**Comment by DasWolke** [comment]
Just looked up for some gifs/pictures, but did not really found anything not nsfw.. Therefore gonna pause this and ask for user submissions.

**Comment by cyberdust2k** [comment]
https://tenor.co/xYV8.gif
I really don't know if they have to be anime related, but it's cute :3

**Comment by cyberdust2k** [comment]
http://data.whicdn.com/images/70218960/large.gif
http://orig15.deviantart.net/5dd6/f/2013/262/a/8/fennekinchu_by_lopmon1990-d6mydzl.gif
http://i.giphy.com/vf5RXzqGIWrZu.gif
Here are another one uwu

**Comment by DasWolke** [comment]
uwu

**Comment by zergling-man** [comment]
These are not necessarily all at their highest resolution.
All results retrieved from Google Image Search "anime tickle gif"

http://vignette2.wikia.nocookie.net/tora-dora/images/2/2f/Minori_trying_to_tickle_Ami.gif
http://pa1.narvii.com/5801/aedc53ea92d4f9d17498674ad24f6d4a6784ce3f_hq.gif
http://i232.photobucket.com/albums/ee231/Asahina-Mikuru/Mikuru%20-%20Gif%20Animados/nocovereu7.gif
http://i.imgur.com/KQwAroV.gif
Get anti-hotlink'd: http://i48.photobucket.com/albums/f213/P0K3Gaming/Lucy%20Tickled_zpsag7ok26i.gif
Have some BL: http://orig13.deviantart.net/0fef/f/2013/242/8/f/sekaiichi_hatsukoi_tickle_fight_by_jerseycar-d6ke74l.gif
http://www.funnyjunk.com/channel/animemanga/Pretty+much+anytime+i+get+tickled/qqwDLdd#b9d6a7_5127494

I've seen these posted before, but reposting them since I don't see them in this thread:
http://new4.fjcdn.com/thumbnails/comments/Completely+agree+the+jiggle+is+what+gets+me+_26f22885a5c15ddb68a019ce46d62904.gif
http://i3.kym-cdn.com/photos/images/original/000/948/122/f23.gif
http://i.imgur.com/rt59hCa.jpg

**Comment by talmarko** [comment]
https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQ_drptyufsPTUZsN3mtumcHoN-DLyjUT8F1UdG_buHyUnO05PiRg

http://pa1.narvii.com/5997/284518131a267b5641cc6f3f9618da18466406e4_hq.gif
http://66.media.tumblr.com/87bd396eb0f6884d421b9ef20dd93d67/tumblr_mnzybe6KKg1qd87hlo1_500.gif
https://s-media-cache-ak0.pinimg.com/originals/c3/a3/a5/c3a3a5ceae3231960846713e0562e6ae.jpg
http://static.fjcdn.com/gifs/Pretty+much+anytime+i+get+tickled+i+dont+like+being_b9d6a7_5127494.gif
https://myanimelist.cdn-dena.com/s/common/uploaded_files/1482023376-9b6557f8f70ce4ba9c2917b78ce76137.gif
